name: Deploy Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  PROJECT_ID: yicfltdrkslghmlbobax

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1.1.1
      # - run: supabase functions deploy upload-note --project-ref $PROJECT_ID
      # - run: supabase functions deploy sign-up --project-ref $PROJECT_ID
